# Generated by Django 4.2.1 on 2023-10-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlistingmodel",
            name="auction_category",
            field=models.ManyToManyField(
                related_name="auctions", to="auctions.categorymodel"
            ),
        ),
    ]
