# Generated by Django 4.2.1 on 2023-10-06 11:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_auctionlistingmodel_auction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
